# -*- coding: utf-8 -*-
"""
Phonetic respellings — what actually gets printed under each phrase.

These are written for an English speaker who does not speak the language and has
no audio. Plain English syllables, hyphenated, no diacritics, no tone numbers.
"Zau6 faai3 hou2 laa3" tells a non-Cantonese speaker nothing; "jow fye hoe lah"
gets them close enough to be recognised.

Two honest limits, both of which argue for recorded audio rather than against
these being useful:

  - Tone is not represented at all. For Mandarin, Cantonese and Vietnamese that
    means a speaker may still be misunderstood. These get you in the
    neighbourhood; they do not get you accurate.
  - English has no clean way to write several of these sounds — Punjabi
    retroflexes, Farsi/Arabic pharyngeals, Vietnamese vowel finals. The
    respellings pick the nearest English shape and accept the loss.

The scholarly romanisations stay in langdata.py, unused by the build, so nothing
is lost if a reviewer wants them back.
"""

PHON = {

# ------------------------------------------------------------- MANDARIN ----
"zh": {
 "s01-01":"waw shr yee-shung, waw lye jyen-chah nin duh yen-jing",
 "s01-02":"ching dzwaw jur-lee",
 "s01-03":"ching bah yen-jing jye shyah-lye",
 "s01-04":"tong mah? nah-lee tong? ching jr yee-shyah",
 "s02-01":"ching bah yen-jing dye shahng",
 "s02-02":"ching nyen nin nung kahn-dow duh dzway shyow duh ee hahng",
 "s02-03":"jee gun show-jr?",
 "s02-04":"kahn duh jyen mah?",
 "s02-05":"kahn-dow gwahng yee-dong ching gow-soo waw",
 "s02-06":"ching kahn waw duh bee-dzuh",
 "s02-07":"nin kahn-dow lyahng guh waw mah?",
 "s02-08":"kahn juh-guh fahng-shyahng gung yen-jong mah?",
 "s03-01":"ching kahn waw duh show-jr, toe boo-yow dong",
 "s03-02":"wahng shahng kahn",
 "s03-03":"wahng shyah kahn",
 "s03-04":"wahng dzwaw kahn",
 "s03-05":"wahng yoe kahn",
 "s03-06":"ching kahn jung chyen-fahng",
 "s04-01":"nin dway yow-woo gwaw-min mah?",
 "s04-02":"waw yow gay nin dyen yen-yow-shway",
 "s04-03":"ching wahng shahng kahn",
 "s04-04":"juh shr yen-jing duh mah-yow, kuh-nung hway tsz-tong jee myow-jong",
 "s04-05":"juh shr sahn-tong yow-shway",
 "s04-06":"nin duh shr-lee hway maw-hoo dah-yweh lyo guh shyow-shr",
 "s04-07":"ching bee shahng yen-jing",
 "s04-08":"boo-yow roe yen-jing",
 "s05-01":"shyah-bah fahng dzye jur-lee, uh-toe kow-juh jur-lee",
 "s05-02":"ching jung-kye yen-jing",
 "s05-03":"toe boo-yow wahng hoe tway",
 "s05-04":"dung hway hun lyahng, ching run yee-shyah",
 "s05-05":"ching kahn waw duh are-dwaw",
 "s05-06":"waw yow pung yee-shyah nin duh yen-pee",
 "s05-07":"kwye how luh",
 "s06-01":"jyen-chah wahn luh, shyeh-shyeh nin",
 "s06-02":"waw-mun hway yong fahn-ee gun nin jyeh-shr jyen-chah jyeh-gwaw",
 "DIP":"roo-gwaw kahn-dow lyahng guh, shr dzun-muh pye duh? ching jr yee-shyah",
 "OPT0":"ee guh", "OPT1":"dzwaw-yoe", "OPT2":"shahng-shyah",
},

# ------------------------------------------------------------ CANTONESE ----
"yue": {
 "s01-01":"ngaw high yee-sahng, ngaw bong nay gim-chah doy ngahn",
 "s01-02":"ching chaw high nee-doh",
 "s01-03":"ching choy-dye ngahn-geng",
 "s01-04":"tung mm tung? bin-doh tung? jee bay ngaw tye",
 "s02-01":"ching dye-fahn ngahn-geng",
 "s02-02":"ching duke nay tye-doh joy sye gaw hong",
 "s02-03":"gay-daw jek sow-jee?",
 "s02-04":"tye mm tye-doh?",
 "s02-05":"gin-doh gwong yuke ching wah ngaw jee",
 "s02-06":"mong-jyu ngaw gaw bay",
 "s02-07":"nay high-my gin-doh leung gaw ngaw?",
 "s02-08":"mong nee-bin wooi mm wooi yim-jung dee?",
 "s03-01":"mong-jyu ngaw jek sow-jee, mm-hoe yuke gaw tow",
 "s03-02":"mong seung",
 "s03-03":"mong lok",
 "s03-04":"mong jaw",
 "s03-05":"mong yow",
 "s03-06":"mong jeng chin-min",
 "s04-01":"nay yow-moe yeuk-mat mun-gum?",
 "s04-02":"ngaw yiu bong nay dick ngahn-yeuk-soy",
 "s04-03":"ching mong seung",
 "s04-04":"nee-dee high ngahn geh mah-yeuk, haw-nahng wooi chee-tung gay miu",
 "s04-05":"nee-dee high sahn-tung yeuk-soy",
 "s04-06":"nay geh see-lick wooi mung dye-hoy luke gaw jung",
 "s04-07":"ching bye-my ngahn",
 "s04-08":"mm-hoe jut ngahn",
 "s05-01":"hah-bah fong high nee-doh, ngahk-tow tip-jyu nee-doh",
 "s05-02":"ching mahk dye doy ngahn",
 "s05-03":"gaw tow mm-hoe heung how toy",
 "s05-04":"gaw dahng hoe gwong, ching yun yat yun",
 "s05-05":"mong-jyu ngaw jek yee-jye",
 "s05-06":"ngaw yiu dim yat dim nay geh ngahn-pay",
 "s05-07":"jow fye hoe lah",
 "s06-01":"gim-chah yune lah, daw-jeh",
 "s06-02":"ngaw-day wooi wun fahn-yick tung nay guy-sick git-gwaw",
 "DIP":"yu-gwaw gin-doh leung gaw, high dim-yeung pye? jee bay ngaw tye",
 "OPT0":"yat gaw", "OPT1":"jaw yow", "OPT2":"seung hah",
},

# -------------------------------------------------------------- PUNJABI ----
"pa": {
 "s01-01":"mane dahk-tar haan, mane tu-hah-dee-yan uh-khan dee jaanch kuh-ran-ga",
 "s01-02":"kir-pa kar-kay ih-thay bay-toe",
 "s01-03":"kir-pa kar-kay eye-nak oo-tah-roe",
 "s01-04":"dard hay? kih-thay? ih-shah-ra kuh-roe",
 "s02-01":"kir-pa kar-kay eye-nak lug-ah-oh",
 "s02-02":"joe sub tone choh-tee line dis-dee hay oh puh-roe",
 "s02-03":"kin-nee-yan oong-lan?",
 "s02-04":"kee ih dis-dah hay?",
 "s02-05":"jay rowsh-nee hil-dee dis-say tahn dus-so",
 "s02-06":"may-ray nuck vull day-koe",
 "s02-07":"kee tu-hah-noo mane doe dis-dah haan?",
 "s02-08":"iss pah-say day-khan tay vudh hoon-da hay?",
 "s03-01":"may-ree oon-gal vull day-koe. sir na hih-lah-oh",
 "s03-02":"oop-par day-koe",
 "s03-03":"hay-thaan day-koe",
 "s03-04":"khub-bay day-koe",
 "s03-05":"suj-jay day-koe",
 "s03-06":"sid-dha saah-muh-nay day-koe",
 "s04-01":"kee tu-hah-noo kih-say duh-vye tone al-ler-jee hay?",
 "s04-02":"mane tu-hah-dee ukh vich boon-daan puh-vaan-ga",
 "s04-03":"kir-pa kar-kay oop-par day-koe",
 "s04-04":"ih ukh soon kuh-ran vah-lee duh-vye hay. kuj sa-kint chubh suk-dee hay",
 "s04-05":"ih boond poot-lee kohl day-vay-gee",
 "s04-06":"nuh-zar lug-bhug chay ghun-tay dhoond-lee ruh-hay-gee",
 "s04-07":"kir-pa kar-kay uh-khan bund kuh-roe",
 "s04-08":"uh-khan na mah-loe",
 "s05-01":"toe-dee ih-thay ruh-koe, mut-tha iss put-tee null lug-ah-oh",
 "s05-02":"uh-khan koh-loe",
 "s05-03":"sir pih-chay na kuh-roe",
 "s05-04":"rowsh-nee tayz hay. tore-ha bar-dasht kuh-roe",
 "s05-05":"may-ray kunn vull day-koe",
 "s05-06":"mane tu-hah-dee puh-luck noo chu-haan-ga",
 "s05-07":"lug-bhug hoe gee-ah",
 "s06-01":"jaanch poo-ree hoe guy. dhun-vaad",
 "s06-02":"uh-seen nuh-tee-jay sum-jhown lye du-bhah-shee-yay dee var-tone kuh-raan-gay",
 "DIP":"jay doe dis-day hun, kih-ven hun? ih-shah-ra kuh-roe",
 "OPT0":"ick", "OPT1":"naal-naal", "OPT2":"oop-par hay-thaan",
},

# ---------------------------------------------------------------- FARSI ----
"fa": {
 "s01-01":"mun dok-tor hass-tam, chesh-mah-yeh show-mah rah moh-eye-eh-neh mee-koh-nam",
 "s01-02":"lot-fan een-jah beh-neh-shee-need",
 "s01-03":"lot-fan ay-nak-eh khod rah bar-dah-reed",
 "s01-04":"dard dah-reed? koh-jah? eh-shah-reh koh-need",
 "s02-01":"lot-fan ay-nak-eh khod rah beh-zah-need",
 "s02-02":"koo-chak-tah-reen khat-tee keh mee-bee-need beh-khah-need",
 "s02-03":"chand an-gosht?",
 "s02-04":"een rah mee-bee-need?",
 "s02-05":"ah-gar noor hah-reh-kat kard beh mun beh-goo-yeed",
 "s02-06":"beh bee-nee-yeh mun neh-gah koh-need",
 "s02-07":"ah-yah mah-rah doe tah mee-bee-need?",
 "s02-08":"vagh-tee beh een tah-raf neh-gah mee-koh-need bad-tar ast?",
 "s03-01":"beh an-gosht-eh mun neh-gah koh-need. sah-reh-tahn rah teh-kahn nah-dah-heed",
 "s03-02":"beh bah-lah neh-gah koh-need",
 "s03-03":"beh pah-een neh-gah koh-need",
 "s03-04":"beh chap neh-gah koh-need",
 "s03-05":"beh rahst neh-gah koh-need",
 "s03-06":"moss-tah-gheem beh jeh-loh neh-gah koh-need",
 "s04-01":"beh dah-roo-yee hass-sah-see-yat dah-reed?",
 "s04-02":"dar chesh-meh show-mah ghat-reh mee-ree-zam",
 "s04-03":"lot-fan beh bah-lah neh-gah koh-need",
 "s04-04":"een ghat-reh bee-hess-see-yeh cheshm ast. mom-ken ast chand sah-nee-yeh beh-soo-zad",
 "s04-05":"een ghat-reh mar-doh-mak rah goh-shahd mee-koh-nad",
 "s04-06":"dee-deh show-mah hoh-doo-deh shesh sah-at tar khah-had bood",
 "s04-07":"lot-fan chesh-mah-neh-tahn rah beh-ban-deed",
 "s04-08":"chesh-mah-neh-tahn rah nah-mah-leed",
 "s05-01":"chah-neh rah een-jah bog-zah-reed va pee-shah-nee rah beh een mee-leh tek-yeh dah-heed",
 "s05-02":"chesh-mah-neh-tahn rah bahz koh-need",
 "s05-03":"sah-reh-tahn rah ah-ghab nah-keh-sheed",
 "s05-04":"noor tond ast. kah-mee tah-ham-mol koh-need",
 "s05-05":"beh goo-sheh mun neh-gah koh-need",
 "s05-06":"pel-keh show-mah rah lams mee-koh-nam",
 "s05-07":"tagh-ree-ban tah-mahm shod",
 "s06-01":"moh-eye-eh-neh tah-mahm shod. moh-teh-shak-keh-ram",
 "s06-02":"bah-rah-yeh tow-zee-heh nah-tah-yej az moh-tar-jem es-teh-fah-deh mee-koh-neem",
 "DIP":"ah-gar doe tah mee-bee-need, cheh-goo-neh gha-rar dah-rand? eh-shah-reh koh-need",
 "OPT0":"yeh-kee", "OPT1":"keh-nah-reh hum", "OPT2":"bah-lah oh pah-een",
},

# --------------------------------------------------------------- ARABIC ----
"ar": {
 "s01-01":"ah-nah at-ta-beeb, sa-af-has ay-nayk",
 "s01-02":"min fad-lik ij-lis hoo-nah",
 "s01-03":"min fad-lik ikh-lah naz-zah-rah-tak",
 "s01-04":"hal tash-oor bee-ah-lam? ah-sheer ee-lah mah-kah-nih",
 "s02-01":"min fad-lik dah naz-zah-rah-tak",
 "s02-02":"ik-rah as-ghar satr tah-rah",
 "s02-03":"kam is-bah-an?",
 "s02-04":"hal tah-rah hah-thah?",
 "s02-05":"akh-bir-nee ee-thah rah-ay-ta ad-dow ya-ta-har-rak",
 "s02-06":"oon-zur ee-lah an-fee",
 "s02-07":"hal tah-rah-nee ith-nayn?",
 "s02-08":"hal yaz-dad soo-an in-da an-na-zar hah-kah-thah?",
 "s03-01":"oon-zur ee-lah is-bah-ee. lah too-har-rik rah-sak",
 "s03-02":"oon-zur ee-lah al-ah-lah",
 "s03-03":"oon-zur ee-lah al-as-fal",
 "s03-04":"oon-zur ee-lah al-ya-sar",
 "s03-05":"oon-zur ee-lah al-ya-meen",
 "s03-06":"oon-zur ee-lah al-ah-mahm mu-bah-sha-ra",
 "s04-01":"hal la-dayk has-sah-see-ya min ayy da-wah?",
 "s04-02":"sa-ah-dah kat-ra fee ay-nak",
 "s04-03":"min fad-lik oon-zur ee-lah al-ah-lah",
 "s04-04":"hah-thi-hi kat-ra mu-khad-di-ra lil-ayn. kad tu-sab-bib wakh-zan li-bid thah-wan",
 "s04-05":"hah-thi-hi al-kat-ra tu-was-see ha-da-kat al-ayn",
 "s04-06":"sa-ta-koon roo-ya-tak da-bah-bee-ya nah-wa sitt sah-aht",
 "s04-07":"min fad-lik agh-mid ay-nayk",
 "s04-08":"lah taf-ruk ay-nayk",
 "s05-01":"dah thak-nak hoo-nah wa-al-sik jab-ha-tak bee-hah-thah ash-sha-reet",
 "s05-02":"if-tah ay-nayk",
 "s05-03":"lah tas-hab rah-sak lil-khalf",
 "s05-04":"ad-dow sah-tee. ta-ham-mal ka-lee-lan",
 "s05-05":"oon-zur ee-lah uth-nee",
 "s05-06":"sa-al-mus jaf-nak",
 "s05-07":"aw-shak-nah ah-lah al-in-ti-hah",
 "s06-01":"in-ta-hah al-fahs. shook-ran lak",
 "s06-02":"sa-nas-ta-een bee-mu-tar-jim li-sharh an-na-tah-ij",
 "DIP":"ee-thah rah-ay-ta ith-nayn, kay-fa yaz-ha-ran? ah-sheer",
 "OPT0":"wah-hid", "OPT1":"jan-ban ee-lah janb", "OPT2":"wah-hid fowk al-ah-khar",
},

# --------------------------------------------------------------- KOREAN ----
"ko": {
 "s01-01":"juh-nun ee-sa-im-ni-da. nu-nul gum-sa-ha-ge-ssum-ni-da",
 "s01-02":"yuh-gee an-ju-say-yo",
 "s01-03":"an-gyung-ul buh-suh ju-say-yo",
 "s01-04":"ah-pu-say-yo? uh-dee-ga ah-pun-jee ga-ree-kyuh ju-say-yo",
 "s02-01":"an-gyung-ul ssu-say-yo",
 "s02-02":"boh-ee-nun ga-jang ja-gun ju-rul il-guh ju-say-yo",
 "s02-03":"son-ga-rak myut gae-yay-yo?",
 "s02-04":"ee-gay boh-ee-say-yo?",
 "s02-05":"bee-chee um-jee-gee-myun mal-ssum-hae ju-say-yo",
 "s02-06":"jay koh-rul boh-say-yo",
 "s02-07":"jay-ga doo myung-u-roh boh-ee-say-yo?",
 "s02-08":"ee-jjoh-gul bol ttae duh sim-han-ga-yo?",
 "s03-01":"jay son-ga-ra-gul boh-say-yo. goh-gae-rul um-jee-gee-jee ma-say-yo",
 "s03-02":"wee-rul boh-say-yo",
 "s03-03":"ah-rae-rul boh-say-yo",
 "s03-04":"wen-jjoh-gul boh-say-yo",
 "s03-05":"oh-run-jjoh-gul boh-say-yo",
 "s03-06":"jung-myun-ul boh-say-yo",
 "s04-01":"yang-mul al-le-ru-gee-ga ee-ssu-say-yo?",
 "s04-02":"nu-nay an-ya-gul nuh-ke-ssum-ni-da",
 "s04-03":"wee-rul bwah ju-say-yo",
 "s04-04":"nun ma-chwee-ya-gim-ni-da. myut choh dong-an tta-kkum-hal su it-ssum-ni-da",
 "s04-05":"ee an-ya-gun dong-gong-ul hwak-jang-shi-kim-ni-da",
 "s04-06":"yak yook-shee-gan dong-an shee-ya-ga hu-ryuh-jim-ni-da",
 "s04-07":"nu-nul ga-ma ju-say-yo",
 "s04-08":"nu-nul bee-bee-jee ma-say-yo",
 "s05-01":"tuh-gul yuh-gee-ay dae-goh ee-ma-rul yuh-gee-ay boo-chee-say-yo",
 "s05-02":"nu-nul ttu-say-yo",
 "s05-03":"muh-ree-rul dwee-roh ppae-jee ma-say-yo",
 "s05-04":"bee-chee bak-ssum-ni-da. joh-gum-man cha-ma ju-say-yo",
 "s05-05":"jay gwee-rul boh-say-yo",
 "s05-06":"nun-kkuh-pu-rul man-jee-ge-ssum-ni-da",
 "s05-07":"guh-ee da dwae-ssum-ni-da",
 "s06-01":"gum-sa-ga kkun-nat-ssum-ni-da. gam-sa-ham-ni-da",
 "s06-02":"tong-yuk-sa-rul tong-hae gyul-gwa-rul sul-myung-hae du-ree-ge-ssum-ni-da",
 "DIP":"doo gae-roh boh-ee-myun uh-ttuh-kay boh-ee-na-yo? ga-ree-kyuh ju-say-yo",
 "OPT0":"ha-na", "OPT1":"jwa-oo", "OPT2":"wee-ah-rae",
},

# ------------------------------------------------------------- JAPANESE ----
"ja": {
 "s01-01":"ee-shee dess. may oh shin-sa-tsu shee-mass",
 "s01-02":"koh-koh nee soo-wat-tay koo-da-sigh",
 "s01-03":"meh-ga-nay oh ha-zoo-shee-tay koo-da-sigh",
 "s01-04":"ee-ta-mee-mass ka? doh-koh ka yoo-bee-sa-shee-tay koo-da-sigh",
 "s02-01":"meh-ga-nay oh ka-kay-tay koo-da-sigh",
 "s02-02":"mee-eh-roo ee-chee-ban chee-sigh gyoh oh yon-day koo-da-sigh",
 "s02-03":"yoo-bee wa nan-bon dess ka?",
 "s02-04":"koh-ray ga mee-eh-mass ka?",
 "s02-05":"hee-ka-ree ga oo-goy-ta-ra oh-shee-eh-tay koo-da-sigh",
 "s02-06":"wa-ta-shee no ha-na oh mee-tay koo-da-sigh",
 "s02-07":"wa-ta-shee ga foo-ta-ree nee mee-eh-mass ka?",
 "s02-08":"koh-chee-ra oh mee-roo toh hee-doh-koo na-ree-mass ka?",
 "s03-01":"wa-ta-shee no yoo-bee oh mee-tay koo-da-sigh. ah-ta-ma wa oo-goh-ka-sa-nigh-day koo-da-sigh",
 "s03-02":"oo-eh oh mee-tay koo-da-sigh",
 "s03-03":"shta oh mee-tay koo-da-sigh",
 "s03-04":"hee-da-ree oh mee-tay koo-da-sigh",
 "s03-05":"mee-ghee oh mee-tay koo-da-sigh",
 "s03-06":"mahs-soo-goo mah-eh oh mee-tay koo-da-sigh",
 "s04-01":"koo-soo-ree no ah-ray-roo-ghee wa ah-ree-mass ka?",
 "s04-02":"meh-goo-soo-ree oh sa-shee-mass",
 "s04-03":"oo-eh oh mee-tay koo-da-sigh",
 "s04-04":"may no ma-soo-ee-ya-koo dess. soo-byoh shee-mee-roo koh-toh ga ah-ree-mass",
 "s04-05":"koh-no meh-goo-soo-ree wa doh-koh oh hee-roh-gay-mass",
 "s04-06":"ya-koo roh-koo-jee-kan, mee-eh-nee-koo-koo na-ree-mass",
 "s04-07":"may oh toh-jee-tay koo-da-sigh",
 "s04-08":"may oh koh-soo-ra-nigh-day koo-da-sigh",
 "s05-01":"ah-goh oh koh-koh nee no-say, hee-tigh oh koh-koh nee tsoo-kay-tay koo-da-sigh",
 "s05-02":"may oh ah-kay-tay koo-da-sigh",
 "s05-03":"ah-ta-ma oh oo-shee-roh nee hee-ka-nigh-day koo-da-sigh",
 "s05-04":"hee-ka-ree ga ma-boo-shee dess. skoh-shee ga-man shtay koo-da-sigh",
 "s05-05":"wa-ta-shee no mee-mee oh mee-tay koo-da-sigh",
 "s05-06":"ma-boo-ta nee sa-wa-ree-mass",
 "s05-07":"moh-soo-goo oh-wa-ree-mass",
 "s06-01":"shin-sa-tsu wa oh-wa-ree dess. ah-ree-ga-toh goh-zigh-ma-shta",
 "s06-02":"kek-ka wa tsoo-ya-koo oh toh-shtay set-soo-may shee-mass",
 "DIP":"foo-ta-tsu mee-eh-roo bye, doh-no yoh nee na-ran-day ee-mass ka? yoo-bee-sa-shee-tay koo-da-sigh",
 "OPT0":"hee-toh-tsu", "OPT1":"sa-yoo", "OPT2":"joh-gay",
},

# ----------------------------------------------------------- VIETNAMESE ----
"vi": {
 "s01-01":"toy lah bahk see, toy seh khahm maht chaw ohng/bah",
 "s01-02":"sin muh-ee ngoy day",
 "s01-03":"sin tao king rah",
 "s01-04":"kaw dow khohng? sin chee choh dow",
 "s02-01":"sin day-oh king vow",
 "s02-02":"sin dawk yawng nyaw nyut mah ohng/bah nyin thay",
 "s02-03":"may ngawn tie?",
 "s02-04":"ohng/bah kaw thay kai nay khohng?",
 "s02-05":"nay-oo thay ang sahng yee chwee-en, sin chaw toy bee-et",
 "s02-06":"sin nyin vow moo-ee toy",
 "s02-07":"ohng/bah kaw thay high ngoo-ee toy khohng?",
 "s02-08":"nyin veh hoong nay kaw nahng huhn khohng?",
 "s03-01":"sin nyin ngawn tie toy. dung kway dow",
 "s03-02":"nyin len",
 "s03-03":"nyin soo-ong",
 "s03-04":"nyin sahng chai",
 "s03-05":"nyin sahng fai",
 "s03-06":"nyin thahng fee-a chuke",
 "s04-01":"ohng/bah kaw yee ung too-ok now khohng?",
 "s04-02":"toy seh nyaw too-ok vow maht",
 "s04-03":"sin nyin len",
 "s04-04":"day lah too-ok tay maht. kaw theh sawt vai yay",
 "s04-05":"too-ok nay seh lahm yahn dohng tu",
 "s04-06":"maht seh muh khwahng sow tee-eng",
 "s04-07":"sin nyam maht lai",
 "s04-08":"dung yoo-ee maht",
 "s05-01":"daht kahm vow day vah ahp chahn vow tahn nay",
 "s05-02":"sin muh maht rah",
 "s05-03":"dung ngah dow rah sow",
 "s05-04":"den rut sahng. sin chee-oo khaw moht choot",
 "s05-05":"sin nyin vow tie toy",
 "s05-06":"toy seh chahm vow mee maht",
 "s05-07":"sahp sawng roy",
 "s06-01":"khahm sawng roy. kahm uhn ohng/bah",
 "s06-02":"choong toy seh nyuh thohng yik vee-en yai thik ket kwah",
 "DIP":"nay-oo thay high hin, choong nahm theh now? sin chee",
 "OPT0":"moht", "OPT1":"kahn nyow", "OPT2":"chen yoo-ee",
},

# -------------------------------------------------------------- TAGALOG ----
"tl": {
 "s01-01":"dok-tor po ah-ko, tee-ting-nan ko ang in-yong ma-nga ma-ta",
 "s01-02":"ma-oo-po po ka-yo ree-to",
 "s01-03":"pa-kee-tang-gal po ang in-yong sa-la-min",
 "s01-04":"ma-sa-kit po ba? ee-too-ro po nin-yo koong sa-an",
 "s02-01":"ee-soo-ot po nin-yo ang in-yong sa-la-min",
 "s02-02":"pa-kee-ba-sa po ang pee-na-ka-ma-lee-eet na lin-yang na-kee-kee-ta nin-yo",
 "s02-03":"ee-lang da-lee-ree po?",
 "s02-04":"na-kee-kee-ta po ba nin-yo ee-to?",
 "s02-05":"sa-bee-hin po nin-yo koong goo-ma-ga-low ang ee-low",
 "s02-06":"ting-nan po nin-yo ang ee-long ko",
 "s02-07":"na-kee-kee-ta po ba nin-yo ah-kong da-la-wa?",
 "s02-08":"mas ma-la-la po ba ka-pag too-mee-ting-in sa ga-nee-tong dee-rek-shon?",
 "s03-01":"ting-nan po nin-yo ang da-lee-ree ko. hoo-wag pong ee-ga-low ang oo-lo",
 "s03-02":"too-ming-in po sa ee-ta-as",
 "s03-03":"too-ming-in po sa ee-ba-ba",
 "s03-04":"too-ming-in po sa ka-lee-wa",
 "s03-05":"too-ming-in po sa ka-nan",
 "s03-06":"too-ming-in po sa ha-rap",
 "s04-01":"my a-ler-jee po ba ka-yo sa ka-hit ah-nong ga-mot?",
 "s04-02":"la-lag-yan ko po nang pa-tak ang ma-ta nin-yo",
 "s04-03":"too-ming-in po sa ee-ta-as",
 "s04-04":"pam-pa-man-hid po ee-to sa ma-ta. ma-ah-ring hoo-map-dee nang ee-lang se-goon-do",
 "s04-05":"pa-la-la-kee-hin po nee-to ang ba-lin-ta-tow nin-yo",
 "s04-06":"ma-la-la-bo po ang pa-ning-in nin-yo nang hoo-mee-git-koo-moo-lang ah-nim na o-ras",
 "s04-07":"ee-pee-kit po nin-yo ang ma-nga ma-ta",
 "s04-08":"hoo-wag pong koos-koo-sin ang ma-ta",
 "s05-01":"ee-pa-tong po ang ba-ba dee-to at ee-dee-kit ang no-o sa bar",
 "s05-02":"ee-moo-lat po nin-yo ang ma-nga ma-ta",
 "s05-03":"hoo-wag pong ee-oo-rong ang oo-lo",
 "s05-04":"ma-lee-wa-nag po ang ee-low. pa-sen-sha po san-da-lee",
 "s05-05":"ting-nan po nin-yo ang ta-ing-a ko",
 "s05-06":"ha-ha-wa-kan ko po ang ta-loo-kap nang ma-ta nin-yo",
 "s05-07":"ma-la-pit na pong ta-pos",
 "s06-01":"ta-pos na po ang pag-soo-soo-ree. sa-la-mat po",
 "s06-02":"ga-ga-mit po ta-yo nang in-ter-pre-ter pa-ra ee-pa-lee-wa-nag ang re-sool-ta",
 "DIP":"koong na-kee-kee-ta nin-yong da-la-wa, pa-ah-no po na-ka-ah-yos? ee-too-ro po nin-yo",
 "OPT0":"ee-sa", "OPT1":"mag-ka-ta-bee", "OPT2":"mag-ka-pa-tong",
},

}
